# Generated by Django 3.2 on 2022-12-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_name'),
        ('reviews', '0003_auto_20221229_2152'),
    ]

    operations = [
    ]
